name: Project Environment Setup
description: Setup project environment with uv
runs:
  using: "composite"
  steps:
    # https://docs.astral.sh/uv/guides/integration/github/
    - name: Install uv
      uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57
      with:
        # The version of uv to install (default: searches for version in config files, then latest)
        version: ""
        enable-cache: true
    - name: Set up Python
      shell: bash
      run: uv python install
    - name: Install Dependencies with uv
      shell: bash
      run: uv sync --all-extras
