name: Build and Test

on:
  pull_request: {}
  push:
    branches:
      - 'main'
      - 'feature/**'
    paths-ignore:
      - '**.md'
      - '_config.yml'
    tags: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: "3.10.0"
          architecture: x64

      - name: Install Dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev

      - run: pipenv run isort --recursive --diff .
      - run: pipenv run black --check .
      - run: pipenv run flake8
      - run: pipenv run mypy
      - name: Python tests with pytest
        run: pipenv run pytest --cov --cov-fail-under=20

  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . -t python_boilerplate:test

      - name: Smoke test docker image
        run: |
          docker run --rm python_boilerplate:test 10
