name: Python CI with pipenv

on:
  pull_request: {}
  push:
    branches:
      - 'main'
      - 'feature/**'
    paths-ignore:
      - '**.md'
      - '_config.yml'
      - '**.tweet'

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/project-environment-setup
      - run: pipenv run isort --recursive --diff .
      - run: pipenv run black --check .
      - run: pipenv run flake8
      - name: Install mypy types
        run: |
          yes | pipenv run mypy --install-types \
          || test $? -eq 2 && echo "Installed mypy types successfully" \
          || echo "Failed to install mypy types"
      - run: pipenv run mypy
      - name: Python Tests with pytest
        run: LOG_LEVEL=INFO pipenv run pytest --cov --cov-fail-under=90 --capture=no --log-cli-level=INFO -n auto
  pyinstaller-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/project-environment-setup
      - name: Build Application Executable Package with PyInstaller
        run: |
          pipenv run pyinstaller --windowed --noconsole \
            --add-data "setup.cfg:." \
            --add-data "python_boilerplate/resources/*:python_boilerplate/resources" \
            --name multithread_and_thread_pool_usage \
            --clean --noconfirm python_boilerplate/demo/multithread_and_thread_pool_usage.py
      - name: Display Built Artifacts
        run: |
          du -s -h *
      - name: Smoke Test PyInstaller Application
        run: ./dist/multithread_and_thread_pool_usage/multithread_and_thread_pool_usage
  docker-image-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          docker build . -t python_boilerplate:smoke-test-tag
          docker inspect python_boilerplate:smoke-test-tag
          echo "Image size: `docker inspect -f "{{ .Size }}" python_boilerplate:smoke-test-tag | numfmt --to=si`"
          docker image ls python_boilerplate:smoke-test-tag
      - name: Smoke Test Docker Image
        run: |
          docker run --rm python_boilerplate:smoke-test-tag param_3_from_command_line
